"""The :func:`validate` façade (PRD §12, SAD §14)."""

from __future__ import annotations

import logging
import time
import uuid
from collections.abc import Iterable, Mapping
from datetime import UTC, datetime
from types import MappingProxyType
from typing import Any

from eduloggen.__version__ import __version__
from eduloggen.core import ConfigError, ValidationError
from eduloggen.models import Dataset, SyntheticDataset
from eduloggen.validation.base import ValidationContext
from eduloggen.validation.registry import DEFAULT_METRICS, get_metric
from eduloggen.validation.report import ValidationReport

__all__ = ["validate"]

logger = logging.getLogger(__name__)


def validate(
    real: Dataset,
    synthetic: Dataset,
    *,
    metrics: Iterable[str] | None = None,
    thresholds: Mapping[str, float] | None = None,
    params: Mapping[str, Mapping[str, Any]] | None = None,
    seed: int = 0,
    real_split: str = "full",
    run_id: str | None = None,
) -> ValidationReport:
    """Compare a real and a synthetic dataset.

    Args:
        real: Real (reference) dataset, sessionized.
        synthetic: Synthetic dataset, sessionized.
        metrics: Metric names; defaults to all built-ins.
        thresholds: Metric name to pass/fail threshold. Metrics without a
            threshold are reported with status ``info``.
        params: Metric name to metric-specific parameters.
        seed: Seed for metrics that subsample.
        real_split: Which part of the real data is the reference (recorded
            in the report, e.g. ``"full"`` or ``"holdout"``).
        run_id: Run identifier; a random one is generated by default.

    Returns:
        The validation report. Threshold failures are reported, not raised.

    Raises:
        ValidationError: If a dataset is not sessionized or ``seed`` is
            invalid.
        ConfigError: If a metric is unknown, listed twice, or a threshold or
            parameter names a metric that is not being computed.
    """
    for label, dataset in (("real", real), ("synthetic", synthetic)):
        if dataset.sessions is None:
            raise ValidationError(
                f"the {label} dataset must be sessionized before validation",
                code="validation_not_sessionized",
                context={"dataset": label},
            )
    if isinstance(seed, bool) or not isinstance(seed, int) or seed < 0:
        raise ValidationError(
            "seed must be a non-negative integer", code="validation_invalid_argument"
        )
    names = list(metrics) if metrics is not None else list(DEFAULT_METRICS)
    if len(set(names)) != len(names):
        raise ConfigError("metrics are listed more than once", code="metric_duplicate")
    selected = [get_metric(name) for name in names]
    limits = dict(thresholds or {})
    for source, keys in (("thresholds", limits), ("params", params or {})):
        stray = sorted(set(keys) - set(names))
        if stray:
            raise ConfigError(
                f"{source} name metrics that are not computed: {', '.join(stray)}",
                code="metric_not_selected",
                context={"metrics": stray},
            )

    context = ValidationContext(
        seed=seed,
        params=MappingProxyType(
            {k: MappingProxyType(dict(v)) for k, v in (params or {}).items()}
        ),
    )
    started = time.perf_counter()
    results = []
    for metric in selected:
        result = metric.compute(real, synthetic, context).evaluate(
            limits.get(metric.name)
        )
        logger.info("%s = %s (%s)", result.name, result.value, result.status)
        results.append(result)
    duration = time.perf_counter() - started

    generation = (
        synthetic.generation if isinstance(synthetic, SyntheticDataset) else None
    )
    return ValidationReport(
        run_id=run_id or uuid.uuid4().hex,
        created_at=datetime.now(UTC),
        real=MappingProxyType(_summary(real)),
        synthetic=MappingProxyType(
            _summary(synthetic)
            | ({"generation": generation.to_dict()} if generation else {})
        ),
        protocol=MappingProxyType(
            {
                "real_split": real_split,
                "synthetic_sessions": synthetic.n_sessions,
                "seed": seed,
                "ids_remapped": (
                    generation.id_strategy == "remap" if generation else None
                ),
            }
        ),
        metrics=tuple(results),
        duration_s=duration,
        eduloggen_version=__version__,
    )


def _summary(dataset: Dataset) -> dict[str, Any]:
    return {
        "dataset_id": dataset.dataset_id,
        "fingerprint": dataset.fingerprint(),
        "schema_version": dataset.schema_version,
        "n_events": dataset.n_events,
        "n_sessions": dataset.n_sessions,
        "n_learners": len(dataset.learner_ids),
    }
